export const dashboardData = {
  weekKey: "2026-W16",
  dateRange: "Apr 21 - Apr 25, 2026",
  status: "Healthy",
  metrics: [
    { label: "Reviews Analyzed", value: "318", trend: "+12% vs last week", trendType: "up" },
    { label: "Avg Rating", value: "4.2", trend: "Stable", trendType: "neutral" },
    { label: "Positive Sentiment", value: "68%", trend: "-2% vs last week", trendType: "down" },
    { label: "Critical Issues", value: "3", trend: "New themes found", trendType: "neutral" },
  ],
  themes: [
    {
      id: 1,
      name: "User Interface and Experience",
      sentiment: "positive",
      mentions: 9,
      confidence: "94%",
      platforms: { apple: 9, google: 0 },
      description: "Reviews praising or criticizing the app's user interface and overall experience",
      quote: "Clean UI",
    },
    {
      id: 2,
      name: "Ease of Use and Trading Experience",
      sentiment: "positive",
      mentions: 8,
      confidence: "88%",
      platforms: { apple: 8, google: 0 },
      description: "Users finding the app easy to use and navigate for trading and investing",
      quote: "Easy to invest",
    },
    {
      id: 3,
      name: "App Performance and Technical Issues",
      sentiment: "negative",
      mentions: 6,
      confidence: "91%",
      platforms: { apple: 1, google: 5 },
      description: "Users experiencing issues with the app's performance, including crashes, freezes, and incorrect calculations",
      quote: "App gets stuck in the middle of trade. Now also application is not opening.",
    },
    {
      id: 4,
      name: "High Brokerage Charges and Fees",
      sentiment: "negative",
      mentions: 5,
      platforms: { apple: 0, google: 5 },
      description: "Users unhappy with the high brokerage charges and fees levied by the app",
      quote: "too much brokerage charges...I have given 2 lack in brokerage charges on FNO",
    },
    {
      id: 5,
      name: "Customer Support and Account Issues",
      sentiment: "negative",
      mentions: 5,
      platforms: { apple: 0, google: 5 },
      description: "Users unhappy with the customer support and experiencing issues with their accounts",
      quote: "Never use this application if you face any problem then customer care not support properly",
    },
  ],
  actions: [
    {
      id: 1,
      priority: "high",
      title: "Fix Login Screen crashes",
      description: "Enhance the login process to reduce crashes and freezes reported by users.",
      category: "Engineering",
    },
    {
      id: 2,
      priority: "medium",
      title: "Streamline Trading Dashboard",
      description: "Simplify navigation and reduce latency on the trading dashboard.",
      category: "Product",
    },
    {
      id: 3,
      priority: "high",
      title: "Robust Error Handling",
      description: "Implement error handling for 'stuck' states to provide recovery options.",
      category: "UA/UX",
    },
  ],
};
